# Default values for dispatcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

container:
  image:
    repository: foxford/mqtt-gateway
    tag: ""

resources:
  limits:
    cpu: 10
    memory: 10Gi
  requests:
    cpu: 0.2
    memory: 400Mi

svc:
  audience: svc.services
  credentials:
    - secret: svc-secret
      subPath: public-key
      mountPath: /path/to/svc/public/key
  authz:
    type: local
    trusted:
      - some-service
  authn:
    key: /path/to/svc/public/key

audiences:
  - audience: foo.bar
    credentials:
      - secret: foobar-der-credentials
        subPath: foobar-public-key
        mountPath: /path/to/foobar/public/key
    authn:
      key: /path/to/foobar/public/key

env:
  APP_CONFIG: /app/App.toml
  APP_AUTHN_ENABLED: 1
  APP_AUTHZ_ENABLED: 1
  APP_DYNSUB_ENABLED: 1
  APP_STAT_ENABLED: 1
  APP_RATE_LIMIT_ENABLED: 1
  DOCKER_VERNEMQ_DISCOVERY_KUBERNETES: 0
  DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR: app=mqtt-gateway

service:
  type: LoadBalancer
  annotations: {}
  ports:
    - name: mqtts
      port: 58883
      targetPort: 8883
    - name: mqtt
      port: 51883
      targetPort: 1883
    - name: metrics
      port: 58888
      targetPort: 8888
    - name: https-standart
      port: 443
      targetPort: 8443
    - name: http-standart
      port: 80
      targetPort: 8080

ingress:
  host: example.org
  tls:
    secretName: tls-certificates

externalLoadBalancer:
  enable: false
  annotations: {}
  ports:
    - name: mqtt
      port: 51883
      targetPort: 1883
    - name: http-standart
      port: 80
      targetPort: 8080
