# Default values for dispatcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

container:
  image:
    repository: foxford/mqtt-gateway
    tag: ""

  volumes:
    - name: config
      configMap:
        name: dispatcher-config
    - name: svc
      secret:
        secretName: svc-pkcs8-der-credentials
    - name: foxford
      secret:
        secretName: iam.foxford-2019-02-04-pkcs8-der-credentials

  volumeMounts:
    - name: config
      mountPath: /app/App.toml
      subPath: App.toml
    - name: foxford
      mountPath: /app/data/keys/iam.foxford.public_key.p8.der
      subPath: iam.foxford.public_key
    - mountPath: /app/data/keys/svc.private_key.p8.der
      name: svc
      subPath: svc.private_key
    - name: svc
      mountPath: /app/data/keys/svc.public_key.p8.der
      subPath: svc.public_key

  resources:
    limits:
      cpu: 10
      memory: 10Gi
    requests:
      cpu: 0.2
      memory: 400Mi

audiences:
  svc.netology-group.services:
    authz:
      type: local
      trusted:
        - http-gateway
        - event
        - cron
        - conference
        - janus-gateway
        - tq
        - telemetry
        - kruonis
        - devops
        - dispatcher
    authn:
      key: data/keys/svc.public_key.p8.der
  foxford.ru:
    authn:
      key: data/keys/iam.foxford.public_key.p8.der
  tenantless:
    authn:
      key: data/keys/iam.foxford.public_key.p8.der

env:
  APP_CONFIG: /app/App.toml
  APP_AUTHN_ENABLED: 1
  APP_AUTHZ_ENABLED: 1
  APP_DYNSUB_ENABLED: 1
  APP_STAT_ENABLED: 1
  APP_RATE_LIMIT_ENABLED: 1
  DOCKER_VERNEMQ_DISCOVERY_KUBERNETES: 0
  DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR: app=mqtt-gateway

config:
  janus_group:

ingress:
  host: netology-group.services
  tls:
    secretName: tls-certificates
