# Default values for dispatcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/mqtt-gateway
    tag: ""

  resources:
    limits:
      cpu: 10
      memory: 10Gi
    requests:
      cpu: 0.2
      memory: 400Mi

  svc:
    audience: foobar
    credentials:
      # foobar-secret-name:
      #   - subPath: private-key
      #     mountPath: /path/to/foobar/private/key
      #   - subPath: public-key
      #     mountPath: /path/to/foobar/public/key
    authz:
      # type: local
      # trusted:
      #   - some-service
    authn:
      # key: /path/to/foobar/public/key

  audiences:
    # - audience: foobar
    #   credentials:
    #     foobar-pem-secret-name:
    #       - subPath: foobar-public-key
    #         mountPath: /path/to/foobar/public/key
    #   authn:
    #     key: /path/to/foobar/public/key

env:
  APP_CONFIG: /app/App.toml
  APP_AUTHN_ENABLED: 1
  APP_AUTHZ_ENABLED: 1
  APP_DYNSUB_ENABLED: 1
  APP_STAT_ENABLED: 1
  APP_RATE_LIMIT_ENABLED: 1
  DOCKER_VERNEMQ_DISCOVERY_KUBERNETES: 0
  DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR: app.kubernetes.io/name=mqtt-gateway

clusterService:
  ports:
    mqtts: 58883
    mqtt: 51883
    metrics: 58888
    wss: 443
    ws: 80
    http: 8081

ingress:
  host: example.org

tls:
  secretName: tls-certificates
