language: erlang
otp_release:
  - 20.3
addons:
  apt:
    packages:
      - lftp
services: docker
git:
  depth: 1
jobs:
  fast_finish: true
  include:
    - stage: check
      name: Tests
      install: make elvis deps plt
      script: make check EUNIT_OPTS=verbose
    - stage: check
      name: Docs
      install: curl https://sh.rustup.rs -sSf | sh -s -- -y && ${HOME}/.cargo/bin/cargo install mdbook --vers 0.2.2 --force
      script: ${TRAVIS_HOME}/.cargo/bin/mdbook build docs && deploy/docs.sh
    - stage: deploy
      name: Kubernetes
      script: deploy/run.sh
stages:
  - name: check
  - name: deploy
    if: (branch = master AND type = push) OR tag IS present
notifications:
  email: false