language: erlang
otp_release:
  - 20.3
addons:
  apt:
    packages:
      - awscli
services: docker
git:
  depth: 1
jobs:
  include:
    - stage: check
      name: Tests
      install: make elvis deps plt
      script: make check EUNIT_OPTS=verbose
    - stage: check
      name: Docs
      install: curl https://sh.rustup.rs -sSf | sh -s -- -y && ${HOME}/.cargo/bin/cargo install mdbook --vers 0.2.3 --force
      script: ${TRAVIS_HOME}/.cargo/bin/mdbook build docs && ./deploy.init.sh && PROJECT='mqtt-gateway' ./deploy/s3-docs.sh
    - stage: deploy
      name: Kubernetes
      script: ./deploy.init.sh && ./deploy/travis-run.sh
stages:
  - name: check
  - name: deploy
    if: (branch = master AND type = push) OR tag IS present
notifications:
  email: false
