language: erlang
otp_release:
  - 20.3
services: docker
git:
  depth: 1
script:
  - cargo test
jobs:
  fast_finish: true
  include:
    - stage: test
      install: make elvis deps plt
      script: make check EUNIT_OPTS=verbose
    - stage: deploy
      before_script: skip
      install: skip
      script: ./deploy/run.sh
stages:
  - name: compile
  - name: test
  - name: deploy
    if: (branch = master AND type = push) OR tag IS present
notifications:
  email: false
