language: erlang
otp_release:
  - 20.3

addons:
  apt:
    packages:
      - awscli

services:
  - docker

git:
  depth: 1

jobs:
  include:
    - stage: check
      name: Tests
      install: make elvis deps plt
      script: make check EUNIT_OPTS=verbose
    - stage: build
      name: Docs
      install:
        - curl https://sh.rustup.rs -sSf | sh -s -- -y
        - ${HOME}/.cargo/bin/cargo install mdbook --vers ^0.4
      script:
        - ${TRAVIS_HOME}/.cargo/bin/mdbook build docs
        - ./deploy.init.sh
        - ./deploy/ci-mdbook.sh
    - stage: build
      name: Build
      script:
        - ./deploy.init.sh
        - ./deploy/ci-install-tools.sh
        - ./deploy/ci-build.sh

stages:
  - name: check
  - name: build
    if: branch = master AND type = push

notifications:
  email: false
