apiVersion: skaffold/v1beta5
kind: Config
build:
  artifacts:
  - image: netologygroup/mqtt-gateway
    docker:
      dockerfile: docker/Dockerfile
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.IMAGE_TAG}}'
  local:
    push: true
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
    - _k8s/mqtt-gateway.yaml
    - _k8s/mqtt-gateway-config.yaml
    - _k8s/mqtt-gateway-headless.yaml
    - _k8s/mqtt-gateway-loadbalancer.yaml
