apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
    - imageName: netologygroup/mqtt-gateway
      workspace: .
      dockerfilePath: docker/Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/*
