apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-gateway.fullname" . }}-headless
  labels:
    {{- include "mqtt-gateway.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mqtt-gateway.selectorLabels" . | nindent 4 }}
  clusterIP: None
