apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "mqtt-gateway.name" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ include "mqtt-gateway.ingressPath" . }}
            backend:
              serviceName: {{ include "mqtt-gateway.serviceName" $ }}
              servicePort: 80
          - path: {{ include "mqtt-gateway.ingressPath" . }}/status
            backend:
              serviceName: {{ include "mqtt-gateway.serviceName" $ }}
              servicePort: 58888

