{{- if .Values.loadBalancerExternal.enable }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-gateway.serviceName" . }}-external
  labels:
    {{- include "mqtt-gateway.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.loadBalancerExternal.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
    {{- range $port := .Values.loadBalancerExternal.ports }}
    - protocol: TCP
      port: {{ get $port "port" }}
      targetPort: {{ get $port "targetPort" }}
      name: {{ get $port "name" }}
    {{- end }}
  selector:
    {{- include "mqtt-gateway.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.loadBalancer.enable }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-gateway.serviceName" . }}-internal
  labels:
    {{- include "mqtt-gateway.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.loadBalancer.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
    {{- range $port := .Values.loadBalancer.ports }}
    - protocol: TCP
      port: {{ get $port "port" }}
      targetPort: {{ get $port "targetPort" }}
      name: {{ get $port "name" }}
    {{- end }}
  selector:
    {{- include "mqtt-gateway.selectorLabels" . | nindent 4 }}
{{- end }}
