apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mqtt-gateway.fullname" . }}
  labels:
    {{- include "mqtt-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  serviceName: {{ include "mqtt-gateway.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "mqtt-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/app-cm: {{ include (print $.Template.BasePath "/app-cm.yaml") . | sha256sum }}
      labels:
        {{- include "mqtt-gateway.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: copy-config-from-volumes
          image: busybox
          command:
          - "sh"
          - "-c"
          - "cp /config-tmp/* /config"
          volumeMounts:
            - name: config-tmp
              mountPath: /config-tmp/vernemq.conf
              subPath: vernemq.conf
            - name: config-tmp
              mountPath: /config-tmp/App.toml
              subPath: App.toml
            - name: config
              mountPath: /config
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 0.1
              memory: 100Mi
            requests:
              cpu: 0.1
              memory: 100Mi
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: APP_AGENT_LABEL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DOCKER_VERNEMQ_DISTRIBUTED_COOKIE
              valueFrom:
                secretKeyRef:
                  name: mqtt-gateway-distributed-cookie
                  key: DOCKER_VERNEMQ_DISTRIBUTED_COOKIE
          volumeMounts:
            - name: config
              mountPath: /vernemq/etc/vernemq.conf
              subPath: vernemq.conf
            - name: data
              mountPath: /data
            - name: config
              mountPath: /app/App.toml
              subPath: App.toml
            - name: tls
              mountPath: /tls
            {{- with .Values.app.svc }}
            {{- $audience := .audience }}
            {{- range $secret, $mounts := .credentials }}
            {{- range $mounts }}
            - name: {{ include "mqtt-gateway.volumeMountName" (list $audience $secret) }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- range .Values.app.audiences }}
            {{- $audience := .audience }}
            {{- range $secret, $mounts := .credentials }}
            {{- range $mounts }}
            - name: {{ include "mqtt-gateway.volumeMountName" (list $audience $secret) }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      volumes:
        - name: config
          emptyDir: {}
        - name: data
          emptyDir: {}
        - name: config-tmp
          configMap:
            name: {{ include "mqtt-gateway.fullname" . }}-app
        - name: tls
          secret:
            secretName: tls-certificates
        {{- with .Values.app.svc }}
        {{- $audience := .audience }}
        {{- range $secret, $mounts := .credentials }}
        - name: {{ include "mqtt-gateway.volumeMountName" (list $audience $secret) }}
          secret:
            secretName: {{ $secret }}
        {{- end }}
        {{- end }}
        {{- range .Values.app.audiences }}
        {{- $audience := .audience }}
        {{- range $secret, $mounts := .credentials }}
        - name: {{ include "mqtt-gateway.volumeMountName" (list $audience $secret) }}
          secret:
            secretName: {{ $secret }}
        {{- end }}
        {{- end }}
