apiVersion: v1
kind: ServiceAccount
metadata:
  name: mqtt-gateway
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mqtt-gateway
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mqtt-gateway
subjects:
  - kind: ServiceAccount
    name: mqtt-gateway
roleRef:
  kind: Role
  name: mqtt-gateway
  apiGroup: rbac.authorization.k8s.io
