apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mqtt-gateway
spec:
  serviceName: mqtt-gateway-headless
  selector:
    matchLabels:
      app: mqtt-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: mqtt-gateway
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mqtt-gateway
          image: netologygroup/mqtt-gateway
          ports:
            - containerPort: 8883
              name: mqtts
            - containerPort: 8443
              name: https
            - containerPort: 1883
              name: mqtt
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: data
              mountPath: /var/lib/vernemq
            - name: conf
              mountPath: /etc/vernemq
            - name: tls
              mountPath: /tls
          lifecycle:
            postStart:
              exec:
                command: ['/bin/sh', '-c', 'chown vernemq:vernemq -R /tls && chown vernemq:vernemq /var/lib/vernemq && chmod u=rwx,go=rx /var/lib/vernemq']
          resources:
            requests:
              cpu: "0.1"
              memory: 200Mi
            limits:
              cpu: "1"
              memory: 2Gi
      volumes:
        - name: conf
          configMap:
            name: mqtt-gateway-config
        - name: tls
          secret:
            secretName: tls-certificates
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs
        resources:
          requests:
            storage: 1Gi
