apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mqtt-gateway
spec:
  serviceName: mqtt-gateway-headless
  selector:
    matchLabels:
      app: mqtt-gateway
  replicas: 3
  template:
    metadata:
      labels:
        app: mqtt-gateway
    spec:
      terminationGracePeriodSeconds: 300
      serviceAccount: mqtt-broker
      containers:
        - name: mqtt-gateway
          image: netologygroup/mqtt-gateway:latest
          ports:
            - containerPort: 8883
              name: mqtts
            - containerPort: 8443
              name: https
            - containerPort: 1883
              name: mqtt
            - containerPort: 8080
              name: http
            - containerPort: 4369
              name: epmd
            - containerPort: 44053
              name: vmq
            - containerPort: 9100
            - containerPort: 9101
            - containerPort: 9102
            - containerPort: 9103
            - containerPort: 9104
            - containerPort: 9105
            - containerPort: 9106
            - containerPort: 9107
            - containerPort: 9108
            - containerPort: 9109
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VERNEMQ_DISCOVERY_KUBERNETES
              value: "1"
            - name: VERNEMQ_KUBERNETES_INSECURE
              value: "1"
            - name: VERNEMQ_KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VERNEMQ_KUBERNETES_APP_LABEL
              value: mqtt-gateway
          volumeMounts:
            - name: data
              mountPath: /var/lib/vernemq
            - name: conf
              mountPath: /etc/vernemq.conf
              subPath: vernemq.conf
            - name: tls
              mountPath: /tls
          resources:
            requests:
              cpu: "0.1"
              memory: 200Mi
            limits:
              cpu: "1"
              memory: 2Gi
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
      volumes:
        - name: conf
          configMap:
            name: mqtt-gateway-configmap
        - name: tls
          secret:
            secretName: tls-certificates
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs
        resources:
          requests:
            storage: 1Gi
