kind: Service
apiVersion: v1
metadata:
  name: mqtt-gateway-loadbalancer
spec:
  selector:
    app: mqtt-gateway
  ports:
    - protocol: TCP
      port: 8883
      targetPort: 8883
      name: mqtts
    - protocol: TCP
      port: 443
      targetPort: 8443
      name: https
    - protocol: TCP
      port: 1883
      targetPort: 1883
      name: mqtt
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  type: LoadBalancer
