allow_anonymous = off
allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = off
max_client_id_size = 150
persistent_client_expiration = never
retry_interval = 5
max_inflight_messages = 0
max_online_messages = -1
max_offline_messages = -1
max_message_size = 0
upgrade_outgoing_qos = off
metadata_plugin = vmq_plumtree
leveldb.maximum_memory.percent = 70
listener.tcp.buffer_sizes = 4096,16384,32768
listener.tcp.my_publisher_listener.buffer_sizes=4096,16384,32768
listener.tcp.my_subscriber_listener.buffer_sizes=4096,16384,32768
listener.max_connections = 10000
listener.nr_of_acceptors = 100
listener.tcp.default = 0.0.0.0:1883
listener.ws.default = 0.0.0.0:8080
listener.vmq.clustering = 0.0.0.0:44053
listener.http.default = 0.0.0.0:8888
listener.tcp.allowed_protocol_versions = 3,4,5
listener.ws.allowed_protocol_versions = 3,4,5
listener.mountpoint = off
systree_enabled = off
systree_interval = 0
shared_subscription_policy = prefer_local
plugins.mqttgw = on
plugins.mqttgw.path = /app/mqttgw
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_diversity = off
plugins.vmq_webhooks = off
plugins.vmq_bridge = off
log.console = console
log.console.level = info
log.syslog = off
log.crash = on
log.crash.file = /vernemq/log/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
nodename = VerneMQ@127.0.0.1
erlang.async_threads = 64
erlang.max_ports = 262144
erlang.distribution_buffer_size = 32MB
distributed_cookie = vmq
