apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-gateway.fullname" . }}-cluster
  labels:
    {{- include "mqtt-gateway.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.clusterService.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    {{- if .Values.clusterService.ports.mqtts }}
    - name: mqtts
      port: {{ .Values.clusterService.ports.mqtts }}
      targetPort: 8883
      protocol: TCP
    {{- end }}
    {{- if .Values.clusterService.ports.mqtt }}
    - name: mqtt
      port: {{ .Values.clusterService.ports.mqtt }}
      targetPort: 1883
      protocol: TCP
    {{- end }}
    {{- if .Values.clusterService.ports.metrics }}
    - name: metrics
      port: {{ .Values.clusterService.ports.metrics }}
      targetPort: 8888
      protocol: TCP
    {{- end }}
    {{- if .Values.clusterService.ports.wss }}
    - name: wss
      port: {{ .Values.clusterService.ports.wss }}
      targetPort: 8443
      protocol: TCP
    {{- end }}
    {{- if .Values.clusterService.ports.ws }}
    - name: ws
      port: {{ .Values.clusterService.ports.ws }}
      targetPort: 8080
      protocol: TCP
    {{- end }}
    {{- if .Values.clusterService.ports.http }}
    - name: http
      port: {{ .Values.clusterService.ports.http }}
      targetPort: 8081
      protocol: TCP
    {{- end }}
  selector:
    {{- include "mqtt-gateway.selectorLabels" . | nindent 4 }}
