apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mqtt-gateway.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.clusterService.ports.mqtt }}
          - path: {{ include "mqtt-gateway.ingressPath" . }}(/|$)(mqtt)
            pathType: Prefix
            backend:
              service:
                name: {{ include "mqtt-gateway.fullname" . }}-cluster
                port:
                  number: {{ .Values.clusterService.ports.ws }}
          {{- end }}
          {{- if .Values.clusterService.ports.metrics }}
          - path: {{ include "mqtt-gateway.ingressPath" . }}(/|$)(status)
            pathType: Prefix
            backend:
              service:
                name: {{ include "mqtt-gateway.fullname" . }}-cluster
                port:
                  number: {{ .Values.clusterService.ports.metrics }}
          {{- end }}
