{{- if .Values.internalService }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-gateway.fullname" . }}-internal
  labels:
    {{- include "mqtt-gateway.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.internalService.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
    {{- if .Values.internalService.ports.mqtt }}
    - name: mqtt
      port: {{ .Values.internalService.ports.mqtt }}
      targetPort: 1883
      protocol: TCP
    {{- end }}
    {{- if .Values.internalService.ports.ws }}
    - name: ws
      port: {{ .Values.internalService.ports.ws }}
      targetPort: 8080
      protocol: TCP
    {{- end }}
    {{- if .Values.clusterService.ports.http }}
    - name: http
      port: {{ .Values.clusterService.ports.http }}
      targetPort: 8081
      protocol: TCP
    {{- end }}
  selector:
    {{- include "mqtt-gateway.selectorLabels" . | nindent 4 }}

{{- end }}
