kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "mqtt-gateway.fullname" . }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
