---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: {{ .Chart.Name }}
spec:
  rules:
  - host: {{ pluck .Values.werf.env .Values.app.host | first | default .Values.app.host._default }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-headless
            port:
              name: http-standart
  tls:
  - hosts:
    - {{ pluck .Values.werf.env .Values.app.host | first | default .Values.app.host._default }}
    secretName: {{ .Chart.Name }}-tls
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-cert
spec:
  secretName: {{ .Chart.Name }}-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: {{ pluck .Values.werf.env .Values.app.host | first | default .Values.app.host._default }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ pluck .Values.werf.env .Values.app.host | first | default .Values.app.host._default }}
