apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mqtt-gateway.fullname" . }}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    port: metrics
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: {{ include "mqtt-gateway.name" . }}
  selector:
    matchLabels:
      {{- include "mqtt-gateway.selectorLabels" . | nindent 6 }}
