---
name: Check Dockerfile standards

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check-dockerfile:
    uses: foxford/reusable-workflows/.github/workflows/check-dockerfile.yml@master
    secrets:
      gh_token: ${{ secrets._GITHUB_TOKEN }}
